import '../models.dart';

const List<Keyword> MOCK_KEYWORDS = [
  Keyword(id: 'kw01', name: 'วัสดุ'),
  Keyword(id: 'kw02', name: 'สารกัมมันตรังสี'),
  Keyword(id: 'kw03', name: 'สิ่งแวดล้อม'),
  Keyword(id: 'kw04', name: 'บุคลากร'),
  Keyword(id: 'kw05', name: 'วัตถุอันตราย'),
  Keyword(id: 'kw06', name: 'มลพิษ'),
  Keyword(id: 'kw07', name: 'โรงงาน'),
  Keyword(id: 'kw08', name: 'ผู้ผลิต'),
  Keyword(id: 'kw09', name: 'ก๊าซอุตสาหกรรม'),
  Keyword(id: 'kw10', name: 'ชำระเงิน'),
  Keyword(id: 'kw11', name: 'ประทานบัตร'),
  Keyword(id: 'kw12', name: 'เหมือง'),
  Keyword(id: 'kw13', name: 'แร่'),
  Keyword(id: 'kw14', name: 'หิน'),
  Keyword(id: 'kw15', name: 'เกลือ'),
  Keyword(id: 'kw16', name: 'อ้อย'),
  Keyword(id: 'kw17', name: 'น้ำตาล'),
  Keyword(id: 'kw18', name: 'SME'),
  Keyword(id: 'kw19', name: 'ยางพารา'),
  Keyword(id: 'kw20', name: 'น้ำเสีย'),
  Keyword(id: 'kw21', name: 'พลังงาน'),
  Keyword(id: 'kw22', name: 'เศรษฐกิจ'),
  Keyword(id: 'kw23', name: 'เทคโนโลยี'),
  Keyword(id: 'kw24', name: 'การเกษตร'),
  Keyword(id: 'kw25', name: 'วิจัย'),
  Keyword(id: 'kw26', name: 'นวัตกรรม'),
  Keyword(id: 'kw27', name: 'กฎหมาย'),
  Keyword(id: 'kw28', name: 'รางวัล'),
  Keyword(id: 'kw29', name: 'โคโรน่า'),
  Keyword(id: 'kw30', name: 'การประชุม'),
  Keyword(id: 'kw31', name: 'การศึกษา'),
  Keyword(id: 'kw32', name: 'ขยะ'),
  Keyword(id: 'kw33', name: 'ust00'), //บุคคลทั่วไป
  Keyword(id: 'kw34', name: 'ust01'), //ผู้ประกอบการ
  Keyword(id: 'kw35', name: 'ระหว่างประเทศ'),
  Keyword(id: 'kw36', name: 'สัญญา'),
  Keyword(id: 'kw37', name: 'การประมง'),
  Keyword(id: 'kw38', name: 'รัฐบาล'),
  Keyword(id: 'kw39', name: 'คอรัปชั่น'),
  Keyword(id: 'kw40', name: 'อากาศ'),
  Keyword(id: 'kw41', name: 'กาแฟ'),
  Keyword(id: 'kw42', name: 'ประกวด'),
  Keyword(id: 'kw43', name: 'ประกาศ'),
  Keyword(id: 'kw44', name: 'สมัครงาน'),
  Keyword(id: 'kw45', name: 'คอมพิวเตอร์'),
];
